config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :publications do
  	resources :comments
  end	
  root "publications#index"

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :publication
end

app/models/publication.rb
class Publication < ApplicationRecord
	#Объявляем, что коменты пренадлежат публикациям и при удалении публикации удалятся коменты
	has_many :comments, dependent: :destroy
	#Проверка на заполненость Заголовка и самого тела публикации
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :publications   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@publication = Publication.find(params[:publication_id])
		@comment = @publication.comments.create(params[:comment].permit(:name, :body))

		redirect_to publication_path(@publication)
	end	

	def destroy
		@publication = Publication.find(params[:publication_id])
		@comment = @publication.comments.find(params[:id])
		@comment.destroy

		redirect_to publication_path(@publication)
	end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end
		
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show] #Для того чтобы незарегистрированный пользователь не мог ничего делать 


	def index
		@publications = Publication.all.order('created_at DESC') #Для отображения всех публикация от новой к старой на главной странице
	end
	
	def new
		@publication = current_user.publications.build #Создание привязки публикации к id юзеру
		#@publication = Publication.new #Cоздали при проверке заполнености и условие при сохранении в методе create
	end

	def create
		#@publication = Publication.new(publication_params) #Создание и сохранение публикации со странички NEW
		@publication = current_user.publications.build(publication_params) #Создание привязки публикации к id юзеру
		if @publication.save
			redirect_to @publication
		else
			render 'new'	
		end
	end

	def show
		@publication = Publication.find(params[:id]) #Просмотр созданой публикации
	end

	def edit
		@publication = Publication.find(params[:id]) 
	end	

	def update
		@publication = Publication.find(params[:id])

		if @publication.update(params[:publication].permit(:title, :body))
			redirect_to @publication
		else
			render 'edit'
		end		
	end	

	def destroy
		@publication = Publication.find(params[:id])
		@publication.destroy

		redirect_to root_path
	end	

private
	def publication_params
		params.require(:publication).permit(:title, :body) #Статические параметры, которые проверяются при создании
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> назад </p>
	</div>
	
	<% if user_signed_in? %>
	<p> <%= link_to 'Удалить', [comment.publication, comment], 
								method: :delete,
								class: "button",
								data: { confirm: 'Вы уверенны?'} %>
									
	</p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@publication, @publication.comments.build]) do |f| %>
	<p>
		<%= f.label :Имя %><br>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :Комментарий %><br>
		<%= f.text_area :body %>
	</p>
	<br>
	<p>
		<%= f.submit "Создать комментарий"%>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="sidebar"> <!-- Создание бокового меню-->
  		<div id="logo">
  			<%= link_to root_path do %>
  				<%= image_tag("logos/logo.png") %>
  			<% end %>	
  		</div>
  		<ul>
  			<li class="category">Website</li>
  			<li><%= link_to "Блог", root_path %></li>
  			<li><%= link_to "Обо мне", about_path %></li>
  		</ul>

  		<ul>
  			<li class="category">Social</li>
  			<li><a href="http://rubyonrails.org/">Ruby on rails</a></li>
  			<li><a href="https://ru.wikipedia.org/wiki/CSS">CSS</a></li>
  			<li><a href="https://ru.wikipedia.org/wiki/HTML">HTML</a></li>
  			<li><a href="https://www.javascript.com/">JavaScript</a></li>
  		</ul>
  		
  	</div>

  	<div id="main_content">
  		<div id="header">
        <% if current_page?(root_path) %>
  			 <p>Все публикации</p>
        <% elsif current_page?(about_path) %>
         <p>Обо мне</p>
        <% else %>
         <%= link_to "Вернуться к публикациям", root_path %>
        <% end %>
           
  			<div class="buttons">

  				<% if user_signed_in? %>
             <%= link_to new_publication_path do %> 
  				  	 <button class="button">Новая публикация</button> 
  					 <% end %>﻿
             <%= link_to edit_user_registration_path do %> 
               <button class="button">Аккаунт</button> 
             <% end %>﻿
          <% end %>﻿

          <% if !user_signed_in? %> 
            <%= link_to new_user_session_path do %>
              <button class="button">Вход</button>
            <% end %>
            <%= link_to new_user_registration_path do %>
              <button class="button">Регистрация</button>
            <% end %>  
          <% else %>
          <%= link_to destroy_user_session_path, :method => :delete do %>
					<button class="button">Выход</button>
          <% end %>
          <% end %>
			</div>
  		</div>

  		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert")%>
  		<% end %>
  	<%= yield %>
  	</div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">		
  		<%= image_tag("logos/profile.jpeg") %>
	</div>

	<div id="content">
		<h1>Hey, I'm Sergiy Bondarenko</h1>
		<p>Welcome to week 2 of my 12 Web Apps in 12 Weeks Challenge.</p>
		<p>This week I built a blog in Rails 4. You're actually on the demo application right now. Cool stuff, right!.</p>
	</div>
</div>

app/views/publications/_form.html.erb
	<!-- Делаем форму для редактирования созданных публикаций-->
	<%= form_for @publication do |f| %>
		<% if @publication.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@publication.errors.count, "error") %> prevented this publication from saving</h2>
				<ul>
					<% @publication.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>	
	<p>
		<%= f.label :title %> <br> <!-- Название текстового поля-->
		<%= f.text_field :title %> <!-- Само текстовое поле-->
	</p>	
		
	<p>
		<%= f.label :body %><br> <!-- Название текстового поля самой публикации-->
		<%= f.text_area :body %> <!-- Сама публикация -->
	</p>

	<p>
		<%= f.submit %> <!-- Кнопка создания публикации -->
	</p>	

	<% end %>	

app/views/publications/edit.html.erb
<div id="page_wrapper">
	<h1>Редактирование публикации</h1>

	<%= render 'form' %>
</div>

app/views/publications/index.html.erb
<% @publications.each do |publication| %>
	<div class="post_wrapper">
		<h2 class="title"> <%= link_to publication.title, publication %> </h2>
		<p class="date">
			<%= publication.created_at.strftime("%B, %d, %Y") %>
		</p>
	</div>
<% end %>

app/views/publications/new.html.erb
<div id="page_wrapper">
	<h1>Новая публикация</h1>

	<%= render 'form' %>
</div>

app/views/publications/show.html.erb
<div id="post_content">
	<h1 class="title">
		<%= @publication.title %>
	</h1>
	
	<p class="date">
		Создано <%= time_ago_in_words(@publication.created_at) %> назад
		<% if @publication.user == current_user %>
		| <%= link_to 'Редактировать', edit_publication_path(@publication) %>
		| <%= link_to 'Удалить', publication_path(@publication), method: :delete, data: { confirm: 'Вы уверены?'} %>
		<% end %>
	</p>
	
	<p class="body">
		<%= @publication.body %>
	</p>

	<div id="comments">
		<h2> <%= @publication.comments.count %> комментариев</h2>
		<%= render @publication.comments %>

		<h3>Добавить комментарий:</h3>
		<%= render "comments/form" %>
	</div>
</div>